DROP TABLE StudentRegistration CASCADE;
DROP TABLE StudentAssessment CASCADE;
DROP TABLE StudentVle CASCADE;
DROP TABLE Assessments CASCADE;
DROP TABLE Vle CASCADE;
DROP TABLE StudentInfo CASCADE;
DROP TABLE Courses CASCADE;
